---
_hotel_id: ASH570
_portal_id: ''
latitude: 42.1856
longitude: -122.66362
name: Ashland Hills Hotel & Suites
email: ''
phone_number: "--"
address:
  street1: 2525 Ashland St
  street2: ''
  state: Oregon
  city: Ashland
  country: United States
  zip_code: '97520'
